In [16]:
import pandas as pd

In [17]:
df =  pd.read_csv("hr_analytics_ibm.csv")

In [18]:
df.head()

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,...,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [19]:
df.isnull().sum()

age                           0
attrition                     0
business_travel               0
daily_rate                    0
department                    0
distance_from_home            0
education                     0
education_field               0
employee_count                0
employee_number               0
environment_satisfaction      0
gender                        0
hourly_rate                   0
job_involvement               0
job_level                     0
job_role                      0
job_satisfaction              0
marital_status                0
monthly_income                0
monthly_rate                  0
num_companies_worked          0
over_18                       0
over_time                     0
percent_salary_hike           0
performance_rating            0
relationship_satisfaction     0
standard_hours                0
stock_option_level            0
total_working_years           0
training_times_last_year      0
work_life_balance             0
years_at_company              0
years_in_current_role         0
years_since_last_promotion    0
years_with_curr_manager       0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.dtypes

age                           int64
attrition                       str
business_travel                 str
daily_rate                    int64
department                      str
distance_from_home            int64
education                     int64
education_field                 str
employee_count                int64
employee_number               int64
environment_satisfaction      int64
gender                          str
hourly_rate                   int64
job_involvement               int64
job_level                     int64
job_role                        str
job_satisfaction              int64
marital_status                  str
monthly_income                int64
monthly_rate                  int64
num_companies_worked          int64
over_18                         str
over_time                       str
percent_salary_hike           int64
performance_rating            int64
relationship_satisfaction     int64
standard_hours                int64
stock_option_level            int64
total_working_years           int64
training_times_last_year      int64
work_life_balance             int64
years_at_company              int64
years_in_current_role         int64
years_since_last_promotion    int64
years_with_curr_manager       int64
dtype: object

In [22]:
df.columns

Index(['age', 'attrition', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_count',
       'employee_number', 'environment_satisfaction', 'gender', 'hourly_rate',
       'job_involvement', 'job_level', 'job_role', 'job_satisfaction',
       'marital_status', 'monthly_income', 'monthly_rate',
       'num_companies_worked', 'over_18', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'standard_hours',
       'stock_option_level', 'total_working_years', 'training_times_last_year',
       'work_life_balance', 'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager'],
      dtype='str')

In [23]:
bins = [18, 25, 35, 45, 60]

labels = ['18-25', '26-35', '36-45', '46-60']

df['age_group'] = pd.cut(
    df['age'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [24]:
df.columns

Index(['age', 'attrition', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_count',
       'employee_number', 'environment_satisfaction', 'gender', 'hourly_rate',
       'job_involvement', 'job_level', 'job_role', 'job_satisfaction',
       'marital_status', 'monthly_income', 'monthly_rate',
       'num_companies_worked', 'over_18', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'standard_hours',
       'stock_option_level', 'total_working_years', 'training_times_last_year',
       'work_life_balance', 'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager', 'age_group'],
      dtype='str')

In [25]:
bins = [0, 3000, 7000, 12000, 20000]
labels = ['Low', 'Medium', 'High', 'Executive']

df['income_group'] = pd.cut(df['monthly_income'], bins=bins, labels=labels)

In [26]:
df.head()

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,...,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager,age_group,income_group
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,0,8,0,1,6,4,0,5,36-45,Medium
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,1,10,3,3,10,7,1,7,46-60,Medium
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,0,7,3,3,0,0,0,0,36-45,Low
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,0,8,3,3,8,7,3,0,26-35,Low
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,1,6,3,3,2,2,2,2,26-35,Medium

In [27]:
df['attrition_flag'] = np.where(df['attrition'] == 'Yes', 1, 0)

In [28]:
import numpy as np

In [29]:
df['attrition_flag'] = np.where(df['attrition'] == 'Yes', 1, 0)

In [30]:
df.head()

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,...,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager,age_group,income_group,attrition_flag
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,8,0,1,6,4,0,5,36-45,Medium,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,10,3,3,10,7,1,7,46-60,Medium,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,7,3,3,0,0,0,0,36-45,Low,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,8,3,3,8,7,3,0,26-35,Low,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,6,3,3,2,2,2,2,26-35,Medium,0

In [31]:
df.to_csv("clean_hr_analytics.csv", index=False)

In [32]:
df.drop(columns=['employee_count', 'over_18', 'standard_hours', 'employee_number'],
        inplace=True)

In [33]:
# Tenure group
df['tenure_group'] = pd.cut(df['years_at_company'],
    bins=[-1, 2, 5, 10, 40],
    labels=['0–2 yrs', '3–5 yrs', '6–10 yrs', '10+ yrs'])

In [34]:
df.to_csv("clean_hr_analytics.csv", index=False)

In [35]:
df.head()

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,environment_satisfaction,gender,...,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager,age_group,income_group,attrition_flag,tenure_group
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,0,1,6,4,0,5,36-45,Medium,1,6–10 yrs
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,3,3,10,7,1,7,46-60,Medium,0,6–10 yrs
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,3,0,0,0,0,36-45,Low,1,0–2 yrs
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,8,7,3,0,26-35,Low,0,6–10 yrs
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,3,2,2,2,2,26-35,Medium,0,0–2 yrs

In [36]:
df['age_group'].value_counts(dropna=False)

age_group
26-35    606
36-45    468
46-60    273
18-25    123
Name: count, dtype: int64

In [37]:
df.to_csv("clean_hr_analytics.csv", index=False)